# Generated by Django 5.2.7 on 2025-10-29 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_section', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('Home', 'Home'), ('Office', 'Office')], default='Home', max_length=20),
        ),
        migrations.AddField(
            model_name='address',
            name='locality',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='address',
            name='mobile',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='address',
            name='street_address',
            field=models.CharField(default='', max_length=200),
        ),
    ]
