# Generated by Django 5.2.7 on 2025-10-18 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0003_brand_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.gender'),
        ),
    ]
