# Generated by Django 5.2.7 on 2025-11-28 08:04

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0009_customuser_dob_customuser_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, default='profile_pics/default.png', max_length=255, null=True, verbose_name='image'),
        ),
    ]
