# Generated by Django 5.2.7 on 2025-10-18 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_alter_category_gender'),
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='gender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adminpanel.gender'),
        ),
    ]
