# Generated by Django 5.2.7 on 2025-11-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='iorderid',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
