# Generated by Django 5.2.7 on 2025-11-08 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_offer_orderitem_discount_value_orderitem_offer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='target_type',
            field=models.CharField(choices=[('product', 'Product'), ('category', 'Category'), ('brand', 'Brand')], max_length=20),
        ),
    ]
