# Generated by Django 5.2.7 on 2025-11-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_orderitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='return_status',
            field=models.CharField(choices=[('None', 'Not Requested'), ('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='None', max_length=20),
        ),
    ]
