# Generated by Django 5.2.7 on 2025-10-25 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0005_category_deleted_at'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='material',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='occasion',
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.material'),
        ),
        migrations.AddField(
            model_name='product',
            name='occasion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='category.occasion'),
        ),
    ]
