# Generated by Django 5.2.7 on 2025-10-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_productimage_is_primary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='long_description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='productvariant',
            name='stock',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='long_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='low_stock_qty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='short_description',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
