# Generated by Django 5.2.7 on 2025-10-18 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_long_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
